/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import java.net.*;
import org.jsoup.Jsoup;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 *
 * @author sapna
 */
public class ct extends javax.swing.JFrame {

    /**
     * Creates new form ct
     */
    public ct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws Exception {
        String u="http://www.javatpoint.com/jsoup-tutorial";
        String v="http://my.horoscope.com/astrology/free-daily-horoscope-scorpio.html";
        URL r=new URL(u);
        URL h=new URL(v);
       // Jsoup.parseBodyFragment()
       org.jsoup.nodes.Document d=Jsoup.parse(h,3000);
//org.jsoup.nodes.Document d1=Jsoup.parseBodyFragment(v);
     //System.out.println(d);
      //  System.out.println(""+d1);
        
      //String doc=d.toString();
      String th="You're ready for dramatic change in your life, Scorpio. It isn't that you're dissatisfied with your career or personal life. Rather, you feel like you're missing out on something great, if you only knew what. Be receptive to whatever opportunities arise and explore them all. You may find the answers you seek through travel or more education. Bring a friend if you're afraid to explore on your own.";
     //Takes only body of the html doc org.jsoup.nodes.Element b=d.body();
    // 
      //org.jsoup.nodes.Element b1=d.body()
       // prints <body> 
      //System.out.println("Body from parse():"+b);
             //prints sthg not body just the URL inside body  System.out.println("Body from parseBodyFragment()"+b1);
       //Doesn't print any thing System.out.println("Body:"+b.ownText());
   //Prints whole doc   org.jsoup.nodes.Document d2=Jsoup.connect(v).get();
        //System.out.println(""+d2);
     //org.jsoup.nodes.Element con=d.getElementById(th);d.get
      //  System.out.println(""+con);
      //  System.out.println(""+d);
     // String s=d.body().text();
      String s1=d.text();
      String s2[];
      s2=s1.split(th);
        System.out.println("Splits:");
        int i=0;
      for(String x:s2)
            System.out.println(++i+""+x);
        //System.out.println(""+s1);
        //System.out.println("Body text"+s);
// System.out.println(""+doc.contains(th));
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
